name: Build SOARE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install w64devkit
      run: |
        curl -L -o w64devkit.zip https://github.com/skeeto/w64devkit/releases/download/v1.23.0/w64devkit-1.23.0.zip
        7z x w64devkit.zip -ow64devkit

    - name: Build with Makefile
      run: ./w64devkit/make.exe

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: soare-binary-windows
        path: bin/soare.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y build-essential binutils

    - name: Build project
      run: make

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: soare-binary-linux
        path: bin/soare
