name: Build SOARE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y build-essential binutils make

    - name: Build project
      run: make

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: soare-binary-linux
        path: bin/soare
