name: Build SOARE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MSYS2
        run: choco install msys2 -y

      - name: Update pacman and install build tools
        shell: bash
        run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm \
            mingw-w64-x86_64-gcc \
            mingw-w64-x86_64-make \
            mingw-w64-x86_64-binutils \
            mingw-w64-x86_64-windres

      - name: Build SOARE
        shell: bash
        run: |
          export PATH="/mingw64/bin:$PATH"
          make

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: soare-binary-windows
          path: bin/soare.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y build-essential binutils make

    - name: Build project
      run: make

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: soare-binary-linux
        path: bin/soare
